name: NPM Publish

on:
  push:
    branches: [main]
  pull_request:
    branches: '*'

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Use Node JS 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install packages
        run: npm install
      # - name: Run test cases
      #   run: npm test

  publish:
    needs: [quality]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Use Node JS 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install packages
        run: npm install
      - name: Generate the build
        run: npm run build
      - name: Release package
        run: npx semantic-release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
